services:
  backend:
   build:
     dockerfile: Dockerfile
   container_name: demo-service
   ports:
     - "8080:8080"
   networks:
     - backend

volumes:
  postgres_data: {}

networks:
  backend:
    driver: bridge